# Generated by Django 2.2.7 on 2021-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordStok',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField(unique=True)),
            ],
        ),
    ]
